# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-release
sudo: false
cache: packages
bioc_required: true

install:
	- ./travis-tool.sh install_r <RcppRoll> <mvtnorm> <MASS> 
	- ./travis-tool.sh install_bioc <BiocInstaller> <BiocCheck> <IRanges> <GenomicRanges> 



script:
	- R CMD build .
	- R CMD check *tar.gz
	- R CMD BiocCheck *tar.gz
