# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-release
use_bioc: true
sudo: false
cache: packages

bioc_packages: BiocInstaller

install:
- ./travis-tool.sh install_r <RcppRoll> <mvtnorm> <MASS> 
- ./travis-tool.sh install_bioc <BiocCheck> <IRanges> <GenomicRanges> 



script:
- R CMD build .
- R CMD check *tar.gz
- R CMD BiocCheck *tar.gz
