# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-release
use_bioc: true
sudo: false
cache: packages
bioc_required: true

before_install:
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix

bioc_packages: 
- IRanges 
- GenomicRanges 
- BiocCheck
- BiocStyle

r_packages: 
- RcppRoll


script:
- R CMD build .
- R CMD check --as-cran *tar.gz
- R CMD BiocCheck *tar.gz
